from flask import Flask, request, render_template
import subprocess
import div_info_parse

app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        horse_url = request.form.get('horse_url')
        if horse_url:
            # Trigger scraper
            result = subprocess.run(['python', 'scraper.py', horse_url], capture_output=True, text=True)
            print(result.stdout)  # Print output for debugging purposes

            # Process the div_info.txt file
            file_path = 'div_info.txt'  # Path to the file generated by scraper.py
            horse_name, scraping_url, career_summary_stats, career_earnings, image_url, racing_direction, racing_surface, racing_condition, stable_name = div_info_parse.find_horse_stats(file_path)
            
            return render_template('result.html', horse_name=horse_name, scraping_url=scraping_url, 
                                   career_summary_stats=career_summary_stats, career_earnings=career_earnings, 
                                   image_url=image_url, racing_direction=racing_direction, racing_surface=racing_surface, 
                                   racing_condition=racing_condition, stable_name=stable_name)
    
    return render_template('index.html')

@app.route('/offer.html', methods=['GET', 'POST'])
def offer_index():
    file_path = 'div_info.txt'  # Path to the file generated by scraper.py
    horse_name, scraping_url, career_summary_stats, career_earnings, image_url, racing_direction, racing_surface, racing_condition, stable_name = div_info_parse.find_horse_stats(file_path)    
    return render_template('offer.html', horse_name=horse_name, scraping_url=scraping_url, 
                                   career_summary_stats=career_summary_stats, career_earnings=career_earnings, 
                                   image_url=image_url, racing_direction=racing_direction, racing_surface=racing_surface, 
                                   racing_condition=racing_condition, stable_name=stable_name)

if __name__ == '__main__':
    app.run(debug=True)
