from flask import Flask, request, render_template, redirect, url_for, session
from werkzeug.security import generate_password_hash, check_password_hash
import subprocess
import div_info_parse

app = Flask(__name__)
app.secret_key = 'your_secret_key'

# In-memory user storage for demo purposes
users = {}

@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        if username in users and check_password_hash(users[username], password):
            session['user'] = username
            # Redirect to the intended search URL after login
            intended_search_url = request.args.get('intended_search_url')
            if intended_search_url:
                return redirect(url_for('search', horse_url=intended_search_url))
            return redirect(url_for('index'))
        else:
            return "Login failed", 401
    return render_template('login.html')

@app.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        if username not in users:
            users[username] = generate_password_hash(password)
            session['user'] = username
            # Redirect to the intended search URL after sign-up
            intended_search_url = request.args.get('intended_search_url')
            if intended_search_url:
                return redirect(url_for('search', horse_url=intended_search_url))
            return redirect(url_for('index'))
        else:
            return "Username already exists", 400
    return render_template('signup.html')

@app.route('/logout')
def logout():
    session.pop('user', None)
    return redirect(url_for('login'))

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        if 'user' not in session:
            return redirect(url_for('login'))
        
        horse_url = request.form.get('horse_url')
        if horse_url:
            return redirect(url_for('search', horse_url=horse_url))
    
    return render_template('index.html')

@app.route('/search', methods=['GET'])
def search():
    horse_url = request.args.get('horse_url')
    if horse_url:
        # Trigger scraper
        result = subprocess.run(['python', 'scraper.py', horse_url], capture_output=True, text=True)
        print(result.stdout)  # Print output for debugging purposes

        # Process the div_info.txt file
        file_path = 'div_info.txt'  # Path to the file generated by scraper.py
        horse_name, scraping_url, career_summary_stats, career_earnings, image_url, racing_direction, racing_surface, racing_condition, stable_name = div_info_parse.find_horse_stats(file_path)
        
        return render_template('result.html', horse_name=horse_name, scraping_url=scraping_url, 
                               career_summary_stats=career_summary_stats, career_earnings=career_earnings, 
                               image_url=image_url, racing_direction=racing_direction, racing_surface=racing_surface, 
                               racing_condition=racing_condition, stable_name=stable_name)
    
    return redirect(url_for('index'))

@app.route('/offer.html', methods=['GET', 'POST'])
def offer_index():
    file_path = 'div_info.txt'  # Path to the file generated by scraper.py
    horse_name, scraping_url, career_summary_stats, career_earnings, image_url, racing_direction, racing_surface, racing_condition, stable_name = div_info_parse.find_horse_stats(file_path)    
    return render_template('offer.html', horse_name=horse_name, scraping_url=scraping_url, 
                                   career_summary_stats=career_summary_stats, career_earnings=career_earnings, 
                                   image_url=image_url, racing_direction=racing_direction, racing_surface=racing_surface, 
                                   racing_condition=racing_condition, stable_name=stable_name)

if __name__ == '__main__':
    app.run(debug=True)
